export default [
	{
		name: "cough",
		displayName: "Cough",
		type: "icon",
		requiresAnswer: [],
		questionText: "Do you have a cough?",
		questionSecondText: "",
		iconText: ["yes", "no"],
		iconColors: ["fb-orange", "fb-green"],
		iconImages: [
			"images/icons/cough.png",
			"images/icons/neutral.png",
		],
	},
	{
		name: "cough-difference",
		displayName: "Cough Difference (Requires Cough)",
		type: "icon",
		requiresAnswer: [{ question: "cough", value: 11 }],
		questionText: "Is it worse than ",
		questionSecondText: "your normal cough?",
		iconText: ["worse", "better", "same"],
		iconColors: ["fb-purple", "fb-green", "fb-orange"],
		iconImages: [
			"images/icons/cough_high.png",
			"images/icons/cough_low.png",
			"images/icons/cough.png",
		],
	},
	{
		name: "cough-severity",
		displayName: "Cough Severity (Requires Cough)",
		type: "icon",
		requiresAnswer: [{ question: "cough", value: 11 }],
		questionText: "How frequent is",
		questionSecondText: "your cough?",
		iconText: ["constantly", "moderately", "light"],
		iconColors: ["fb-purple", "fb-orange", "fb-green"],
		iconImages: [
			"images/icons/freq3.png",
			"images/icons/freq2.png",
			"images/icons/freq1.png",
		],
	},
	{
		name: "cough-progress",
		displayName: "Cough Progress (Requires Cough)",
		type: "icon",
		requiresAnswer: [{ question: "cough", value: 11 }],
		questionText: "Is your cough",
		questionSecondText: "getting worse?",
		iconText: ["worsening", "improving", "same"],
		iconColors: ["fb-purple", "fb-green", "fb-orange"],
		iconImages: [
			"images/icons/cough_high.png",
			"images/icons/cough_low.png",
			"images/icons/cough.png",
		],
	},
	{
		name: "breathing",
		displayName: "Breathing",
		type: "icon",
		requiresAnswer: [],
		questionText: "Is it difficult to breath?",
		questionSecondText: "",
		iconText: ["yes", "no"],
		iconColors: ["fb-orange", "fb-green"],
		iconImages: [
			"images/icons/breath_worse.png",
			"images/icons/breath_good.png",
		],
	},
	{
		name: "breathing-progress",
		displayName: "Breathing Progress (Requires Breathing)",
		type: "icon",
		requiresAnswer: [{ question: "breathing", value: 11 }],
		questionText: "Is your breathing",
		questionSecondText: "getting worse?",
		iconText: ["worsening", "improving", "same"],
		iconColors: ["fb-purple", "fb-green", "fb-orange"],
		iconImages: [
			"images/icons/breath_worse.png",
			"images/icons/breath_good.png",
			"images/icons/breath_same.png",
		],
	},
	{
		name: "breathing-resting",
		displayName: "Breathing Resting (Requires Breathing)",
		type: "icon",
		requiresAnswer: [{ question: "breathing", value: 11 }],
		questionText: "Is it difficult to breath",
		questionSecondText: "while resting?",
		iconText: ["yes", "no"],
		iconColors: ["fb-orange", "fb-green"],
		iconImages: [
			"images/icons/breath_worse.png",
			"images/icons/breath_good.png",
		],
	},
	{
		name: "breathing-concern",
		displayName: "Breathing Concern (Requires Breathing)",
		type: "icon",
		requiresAnswer: [{ question: "breathing", value: 11 }],
		questionText: "Are you concerned with",
		questionSecondText: "your breathing?",
		iconText: ["concerned", "no"],
		iconColors: ["fb-orange", "fb-green"],
		iconImages: [
			"images/icons/worry.png",
			"images/icons/neutral.png",
		],
	},
	{
		name: "fever",
		displayName: "Fever",
		type: "icon",
		requiresAnswer: [],
		questionText: "Do you have a fever?",
		questionSecondText: "",
		iconText: ["yes", "no", "don't know"],
		iconColors: ["fb-orange", "fb-green", "fb-slate"],
		iconImages: [
			"images/icons/fever_high.png",
			"images/icons/healthy.png",
			"images/icons/fever_unk.png",
		],
	},
	{
		name: "fever-concern",
		displayName: "Fever Concern (Requires Fever)",
		type: "icon",
		requiresAnswer: [{ question: "fever", value: 11 }],
		questionText: "Are you concerned",
		questionSecondText: "about your fever?",
		iconText: ["concerned", "no"],
		iconColors: ["fb-orange", "fb-cyan"],
		iconImages: [
			"images/icons/worry.png",
			"images/icons/neutral.png",
		],
	},
	{
		name: "thermometer",
		displayName: "Have a thermometer?",
		type: "icon",
		requiresAnswer: [],
		questionText: "Do you have a",
		questionSecondText: "thermometer?",
		iconText: ["yes", "no"],
		iconColors: ["fb-green", "fb-orange"],
		iconImages: [
			"images/icons/thermometer.png",
			"images/icons/thermometer_no.png",
		],
	},
	{
		name: "fever-confirm",
		displayName: "Confirm Fever (Requires Fever)",
		type: "icon",
		requiresAnswer: [{ question: "fever", value: "determined by code" }],
		questionText: "You selected xxxx",
		questionSecondText: "Is this correct?",
		iconText: ["","","yes"],
		iconColors: ["fb-black","fb-black","fb-green"],
		iconImages: ["images/icons/prefer_cold.png","images/icons/prefer_cold.png","images/icons/prefer_cold.png"],
	},
	{
		name: "lethargy",
		displayName: "Lethargy",
		type: "icon",
		requiresAnswer: [],
		questionText: "Do you feel tired?",
		questionSecondText: "",
		iconText: ["yes", "no"],
		iconColors: ["fb-orange", "fb-green"],
		iconImages: [
			"images/icons/lethargy.png",
			"images/icons/lethargy_no.png",
		],
	},
	{
		name: "lethargy-severity",
		displayName: "Lethargy Severity  (Requires Lethargy)",
		type: "icon",
		requiresAnswer: [{ question: "lethargy", value: 11 }],
		questionText: "How severe is your",
		questionSecondText: "tiredness",
		iconText: ["bed bound", "mild", "moderate"],
		iconColors: ["fb-purple", "fb-green", "fb-orange"],
		iconImages: [
			"images/icons/lethargy_bed.png",
			"images/icons/lethargy_mild.png",
			"images/icons/lethargy.png",
		],
	},
];
